services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gravityly-frontend
    ports:
      - "8080:80" # Acessível no navegador via localhost:8080
    restart: unless-stopped