services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "mkdir -p /var/db && touch /var/db/database.sqlite && php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - sqlite_data:/var/db
      - storage_data:/var/www/storage/app/public
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/db/database.sqlite
      - APP_URL=http://localhost:8000
      - APP_ENV=local
      - APP_DEBUG=true

volumes:
  sqlite_data:
  storage_data:
