FROM php:8.4-cli-alpine

RUN apk add --no-cache \
    git curl libpng-dev libzip-dev zip unzip oniguruma-dev \
    sqlite-dev \
    freetype-dev libjpeg-turbo-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_sqlite mbstring zip gd bcmath

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY composer.json composer.lock ./
RUN composer install --prefer-dist --no-scripts

COPY . .

RUN mkdir -p database \
    && touch database/database.sqlite

EXPOSE 8000

CMD php artisan serve --host=0.0.0.0 --port=8000